cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.jest-cache
    - $HOME/.npm
    - $HOME/.nvm/.cache
    - $HOME/phpunit-bin

notifications:
  email:
    on_success: never
    on_failure: change

language: php

dist: trusty

addons:
  apt:
    packages:
    - libxml2-utils

branches:
  only:
    - master
    - develop
    - /^\d+\.\d+$/

env:
  global:
    - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true

before_install:
  - nvm install
  - nvm use

install:
  - npm install
  - export DEV_LIB_PATH=vendor/xwp/wp-dev-lib/scripts
  - export DIFF_HEAD=HEAD
  - source "$DEV_LIB_PATH/travis.install.sh"

jobs:
  fast_finish: true
  include:
    - stage: lint
      name: Lint (PHP, JavaScript, and configuration files)
      php: "7.4"
      env: WP_VERSION=latest DEV_LIB_ONLY=xmllint,phpsyntax
      script:
        - source "$DEV_LIB_PATH/travis.script.sh"
        - npm run lint

    - stage: deploy to staging
      if: (NOT type IN (pull_request))
      script: skip
      deploy:
        skip_cleanup: true
        # deploy builds in develop to the pantheon dev environment
        provider: script
        script: bash bin/deploy.sh
        on:
          branch: develop
